/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Education = IDL.Record({
  'endDate' : IDL.Text,
  'school' : IDL.Text,
  'description' : IDL.Text,
  'degree' : IDL.Text,
  'startDate' : IDL.Text,
});
export const WorkExperience = IDL.Record({
  'endDate' : IDL.Text,
  'description' : IDL.Text,
  'company' : IDL.Text,
  'position' : IDL.Text,
  'startDate' : IDL.Text,
});
export const PersonalInfo = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'website' : IDL.Text,
  'phone' : IDL.Text,
  'location' : IDL.Text,
});
export const Resume = IDL.Record({
  'education' : IDL.Vec(Education),
  'workExperience' : IDL.Vec(WorkExperience),
  'lastUpdated' : IDL.Int,
  'summary' : IDL.Text,
  'template' : IDL.Text,
  'personalInfo' : PersonalInfo,
  'skills' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'createResume' : IDL.Func([IDL.Text, Resume], [], []),
  'getAllResumes' : IDL.Func([], [IDL.Vec(Resume)], ['query']),
  'getResume' : IDL.Func([IDL.Text], [Resume], ['query']),
  'getResumesByTemplate' : IDL.Func([IDL.Text], [IDL.Vec(Resume)], ['query']),
  'updateResume' : IDL.Func([IDL.Text, Resume], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Education = IDL.Record({
    'endDate' : IDL.Text,
    'school' : IDL.Text,
    'description' : IDL.Text,
    'degree' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const WorkExperience = IDL.Record({
    'endDate' : IDL.Text,
    'description' : IDL.Text,
    'company' : IDL.Text,
    'position' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const PersonalInfo = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'website' : IDL.Text,
    'phone' : IDL.Text,
    'location' : IDL.Text,
  });
  const Resume = IDL.Record({
    'education' : IDL.Vec(Education),
    'workExperience' : IDL.Vec(WorkExperience),
    'lastUpdated' : IDL.Int,
    'summary' : IDL.Text,
    'template' : IDL.Text,
    'personalInfo' : PersonalInfo,
    'skills' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'createResume' : IDL.Func([IDL.Text, Resume], [], []),
    'getAllResumes' : IDL.Func([], [IDL.Vec(Resume)], ['query']),
    'getResume' : IDL.Func([IDL.Text], [Resume], ['query']),
    'getResumesByTemplate' : IDL.Func([IDL.Text], [IDL.Vec(Resume)], ['query']),
    'updateResume' : IDL.Func([IDL.Text, Resume], [], []),
  });
};

export const init = ({ IDL }) => { return []; };