/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Education {
  'endDate' : string,
  'school' : string,
  'description' : string,
  'degree' : string,
  'startDate' : string,
}
export interface PersonalInfo {
  'name' : string,
  'email' : string,
  'website' : string,
  'phone' : string,
  'location' : string,
}
export interface Resume {
  'education' : Array<Education>,
  'workExperience' : Array<WorkExperience>,
  'lastUpdated' : bigint,
  'summary' : string,
  'template' : string,
  'personalInfo' : PersonalInfo,
  'skills' : Array<string>,
}
export interface WorkExperience {
  'endDate' : string,
  'description' : string,
  'company' : string,
  'position' : string,
  'startDate' : string,
}
export interface _SERVICE {
  'createResume' : ActorMethod<[string, Resume], undefined>,
  'getAllResumes' : ActorMethod<[], Array<Resume>>,
  'getResume' : ActorMethod<[string], Resume>,
  'getResumesByTemplate' : ActorMethod<[string], Array<Resume>>,
  'updateResume' : ActorMethod<[string, Resume], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];